language: node_js
node_js:
  - "10"
before_script:
  - npm pack
after_success:
  - npm run coveralls
deploy:
  - provider: releases
    api_key: $GITHUB_DEPLOYMENT_KEY
    file_glob: true
    file: "**/*.tgz"
    skip_cleanup: true
    draft: true
    name: $TRAVIS_BRANCH
    body: $TRAVIS_COMMIT_MESSAGE
    on:
      tags: true
